version: '3.7'
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8000:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
networks:
  default:
    external:
      name: backend
volumes:
  mariadb-data: null
