services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - './db-data:/var/lib/mysql'
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
